title: Vidhai
baseurl: https://webopsiiitdmk.github.io/vidhai
copyright: '&copy; 2020 Vidhai. All rights reserved.'

params:
  description: A non-profit organization.

  sections:
    - carousel
    - intro
    - story
    - programmes
    - explained 
    - structure
    - activities
    - join us
    - support
    - contact


  fonts:
    heading: Prompt
    body: Nunito

social:
  address: Indian Institute of Information Technology, Design and Manufacturing, Kancheepuram, Tamil Nadu - 600127
  email: vidhai.iiitdm@gmail.com
  instagram: vidhai_iiitdm
  phone: '9444695092'

disableKinds:
  - section
  - taxonomy
  - term
